-- queries_task3_exact.sql
-- Exact queries taken from swiggy.pdf without any modification.

-- 1) Display all customers who live in 'Delhi'.
SELECT
  customer_id,
  name,
  city
FROM
  customers
WHERE
  city = 'delhi';

-- 2) Find the average rating of all restaurants in 'Mumbai'
SELECT
  AVG(restaurants.rating) AS Avg_Rating
FROM
  restaurants
WHERE
  restaurants.city = 'Mumbai';

-- 3) List all customers who have placed at least one order.
SELECT
  customers.customer_id,
  customers.name
FROM
  orders
  JOIN customers ON orders.customer_id = customers.customer_id
GROUP BY
  customers.customer_id
HAVING
  COUNT(orders.order_id) > 0;

-- 4) Display the total number of orders placed by each customer.
SELECT
  customers.customer_id,
  customers.name,
  COUNT(orders.order_id) Total_Orders
FROM
  customers
  RIGHT JOIN orders USING (customer_id)
GROUP BY
  customers.customer_id,
  customers.name;

-- 5) Find the total revenue generated by each restaurant.
SELECT
  restaurants.restaurant_id,
  restaurants.name,
  SUM(orders.total_amount) AS Total_Revenue
FROM
  orders
  RIGHT JOIN restaurants ON orders.restaurant_id = restaurants.restaurant_id
GROUP BY
  restaurants.restaurant_id,
  restaurants.name;

-- 6) Find the top 5 restaurants with the highest average rating.
SELECT
  restaurants.name,
  AVG(restaurants.rating) Avg_Rating
FROM
  restaurants
GROUP BY
  restaurants.name
ORDER BY
  AVG(restaurants.rating) DESC
LIMIT 5;

-- 7) Display all customers who have never placed an order.
SELECT
  customers.customer_id,
  customers.name
FROM
  customers
  LEFT JOIN orders USING (customer_id)
WHERE
  order_id IS NULL;

-- 8) Find the number of orders placed by each customer in 'Mumbai'.
SELECT
  customers.name,
  COUNT(orders.order_id) Total_Orders
FROM
  customers
  JOIN orders USING (customer_id)
WHERE
  customers.city = 'mumbai'
GROUP BY
  customers.name;

-- 9) Display all orders placed in the last 30 days.
SELECT *
FROM orders
WHERE order_date >= DATE_SUB(
    (SELECT MAX(order_date) FROM orders),
    INTERVAL 30 DAY
);

-- 10) List all delivery partners who have completed more than 1 delivery.
SELECT
  deliverypartners.name,
  COUNT(orderdelivery.order_delivery_id) Total_Orders_Delivered
FROM
  deliverypartners
  JOIN orderdelivery USING (partner_id)
  JOIN orders USING (order_id)
GROUP BY
  deliverypartners.name
HAVING
  COUNT(orderdelivery.order_delivery_id) > 1;

-- 11) Find the customers who have placed orders on exactly three different days.
SELECT
  customers.name,
  COUNT(DISTINCT orders.order_date) Orders
FROM
  orders
  JOIN customers USING (customer_id)
GROUP BY
  customers.name
HAVING
  COUNT(DISTINCT orders.order_date) = 3;

-- 12) Find the delivery partner who has worked with the most different customers.
SELECT
  deliverypartners.partner_id,
  deliverypartners.name,
  COUNT(DISTINCT orders.customer_id) Total_Order_Delivered
FROM
  deliverypartners
  JOIN orderdelivery USING (partner_id)
  JOIN orders USING (order_id)
GROUP BY
  deliverypartners.partner_id,
  deliverypartners.name
ORDER BY
  COUNT(DISTINCT orders.customer_id) DESC
LIMIT 1;

-- 13) Customers with the same city & same restaurant but different order dates.
SELECT DISTINCT
  t1.customer_id,
  t1.customer_name,
  t1.customer_city,
  t1.restaurant_id,
  t1.restaurant_name,
  t1.order_date,
  t2.customer_id AS customer2_id,
  t2.customer_name AS customer2_name,
  t2.order_date AS other_order_date
FROM
  (
    SELECT
      cu.customer_id,
      cu.name AS customer_name,
      cu.city AS customer_city,
      r.restaurant_id,
      r.name AS restaurant_name,
      o.order_date
    FROM
      orders o
      JOIN customers cu ON cu.customer_id = o.customer_id
      JOIN restaurants r ON r.restaurant_id = o.restaurant_id
  ) t1
  JOIN (
    SELECT
      cu.customer_id,
      cu.name AS customer_name,
      cu.city AS customer_city,
      r.restaurant_id,
      r.name AS restaurant_name,
      o.order_date
    FROM
      orders o
      JOIN customers cu ON cu.customer_id = o.customer_id
      JOIN restaurants r ON r.restaurant_id = o.restaurant_id
  ) t2
    ON t1.customer_city = t2.customer_city
   AND t1.restaurant_id = t2.restaurant_id
   AND t1.customer_id <> t2.customer_id
   AND t1.order_date <> t2.order_date;
